version: '3.8'

services:
  assistant-of-devil-backend:
    build:
      args:
        user: $USER_NAME
        uid: $UID
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '${API_OUTSIDE_PORT}:${API_INSIDE_PORT}'
    command: sh -c "npm install && npm run dev:windows"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
