version: '3.8'

services:
    assistant-of-devil-backend:
        build:
            args:
                user: $USER_NAME
                uid: $UID
            context: .
        working_dir: /app
        volumes:
            - ./:/app
        env_file:
            - .env
        ports:
            - '${API_OUTSIDE_PORT}:${API_INSIDE_PORT}'
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
